name: Ruber build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write
  id-token: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: write
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Cache
      - name: Install toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      # Build and test
      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      # Clippy
      - name: Add Clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Run Clippy
        uses: giraffate/clippy-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Audit
      - name: Audit checkout
        uses: actions/checkout@v4

      - name: Audit check
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
